"""MCP stdio adapter exposing the bounded agent interface (R1).

The MCP SDK is an optional dependency: this module imports it lazily so a base
install without the ``mcp`` extra keeps ``import coordinate`` and every other
CLI path working. Only ``coordinate mcp serve`` touches this module.

Every tool returns the stable R1 envelope through both ``structured_content``
and an equivalent JSON ``TextContent`` so hosts that cannot consume structured
content still see the same contract. Failures set ``is_error=true``; the
facade is the only error-sanitization boundary, and this adapter adds a
last-resort catch so an unexpected exception can never leak its ``str(e)`` or
traceback onto the wire through the SDK's default rendering.

Input/output schemas are generated by the SDK from the public pydantic models
below (no SDK private manager is touched):

- required fields are declared without defaults so ``tools/list`` advertises a
  non-empty ``required`` set;
- ``routing_request`` is a typed object listing exactly the five raw builder
  fields with ``required_capabilities`` required and ``additionalProperties:
  false`` (extra fields fail closed at the SDK layer and again in the facade);
- the return annotation ``Envelope`` publishes the envelope ``outputSchema``
  with required ``ok, data, error``; the runtime still returns a
  ``CallToolResult`` whose ``structured_content`` the SDK validates against
  that schema (the SDK's documented passthrough for ``CallToolResult``).
"""

from __future__ import annotations

import json
import logging
from typing import Any, Callable

from pydantic import BaseModel, ConfigDict

from . import __version__
from .agent_interface import AgentInterface

logger = logging.getLogger("coordinate.mcp_server")

# R5B typed tool names: single authority for the six tools that take one
# flat ``input`` object (pydantic ``extra="forbid"`` models). Registration
# below, the shared stdio/remote call-shape gate (C2) and the remote
# middleware unwrap all read this set — no second handwritten copy.
TOOL_TASK_CREATE_RECORD = "coordinate.task_create_record"
TOOL_COMPLETION_PREPARE = "coordinate.completion_prepare"
TOOL_COMPLETION_PREFLIGHT = "coordinate.completion_preflight"
TOOL_COMPLETION_CLAIM = "coordinate.completion_claim"
TOOL_COMPLETION_APPLY = "coordinate.completion_apply"
TOOL_COMPLETION_CONSUME = "coordinate.completion_consume"
TOOL_CHANNEL_CREATE = "coordinate.channel_create"

TYPED_INPUT_TOOLS: frozenset[str] = frozenset(
    {
        TOOL_TASK_CREATE_RECORD,
        TOOL_COMPLETION_PREPARE,
        TOOL_COMPLETION_PREFLIGHT,
        TOOL_COMPLETION_CLAIM,
        TOOL_COMPLETION_APPLY,
        TOOL_COMPLETION_CONSUME,
        TOOL_CHANNEL_CREATE,
    }
)

# Single authority for the eleven tool names shared by stdio (R1) and the
# remote streamable HTTP adapter (R3): registration, policy validation and
# tests all read this set instead of hard-coding a second copy.
MCP_TOOL_NAMES: frozenset[str] = frozenset(
    {
        "coordinate.operator_pending",
        "coordinate.workspace_audit",
        "coordinate.runtime_request_submit",
        "coordinate.runtime_job_get",
        "coordinate.runtime_agent_list",
    }
) | TYPED_INPUT_TOOLS

_INTERNAL_ENVELOPE: dict[str, Any] = {
    "ok": False,
    "data": None,
    "error": {"code": "internal", "message": "internal error"},
}


class RoutingRequestInput(BaseModel):
    """Raw routing builder fields accepted from a tool caller (R1).

    ``routing_request_id`` and contract/policy versions are computed by
    ``build_routing_request()`` on the server side and are deliberately not
    accepted here; unknown fields fail closed via ``extra="forbid"``.
    """

    required_capabilities: list[str]
    executor_definition_id: str | None = None
    preferred_host_id: str | None = None
    operator_override_agent_id: str | None = None
    operator_override_reason: str | None = None

    model_config = ConfigDict(extra="forbid")


class TaskCreateRecordInput(BaseModel):
    """Narrow scalar contract for the task.create record half (R5B).

    The deployed checklist envelope and fingerprints are re-derived server
    side from the registered workspace's deployed bytes; the caller supplies
    only scalars. No ``payload`` dict, no arbitrary path, no actor and no
    full envelope: actor is fixed to the request-scoped principal by the
    facade, and fingerprint/UUID/path formats are validated by the existing
    split-operation domain validators.
    """

    workspace_id: str
    operation_id: str
    input_fingerprint: str
    before_fingerprint: str
    after_fingerprint: str
    task_id: str
    plan_doc: str
    title: str | None = None
    phase: str | None = None
    owner: str | None = None
    branch: str | None = None
    idempotency_key: str | None = None

    model_config = ConfigDict(extra="forbid")


class CompletionPrepareInput(BaseModel):
    """prepare accepts workspace/task only; requester and authorized_actor
    are fixed to the request-scoped principal actor (never caller-set)."""

    workspace_id: str
    task_id: str

    model_config = ConfigDict(extra="forbid")


class CompletionPreflightInput(BaseModel):
    """Read-only receipt preflight. ``workspace_id`` is required so the
    remote middleware can scope first; the domain then binds the receipt."""

    workspace_id: str
    receipt_id: str

    model_config = ConfigDict(extra="forbid")


class CompletionClaimInput(BaseModel):
    """Reserve: authorized -> claimed with before/expected-after fingerprints."""

    workspace_id: str
    receipt_id: str
    task_id: str
    before_fingerprint: str
    expected_after_fingerprint: str

    model_config = ConfigDict(extra="forbid")


class CompletionApplyInput(BaseModel):
    """Acknowledge: claimed -> applied with the actual after fingerprint."""

    workspace_id: str
    receipt_id: str
    task_id: str
    after_fingerprint: str

    model_config = ConfigDict(extra="forbid")


class CompletionConsumeInput(BaseModel):
    """Terminal: re-verify the deployed harness and write task.done.

    ``workspace_id`` is required so the remote middleware can scope first;
    the domain then binds it against the receipt payload.
    """

    workspace_id: str
    receipt_id: str
    verification: str | None = None

    model_config = ConfigDict(extra="forbid")


class ChannelCreateInput(BaseModel):
    """Narrow provisioning request; platform and actor are server-derived."""

    workspace_id: str
    channel_name: str
    idempotency_key: str

    model_config = ConfigDict(extra="forbid")


class Envelope(BaseModel):
    """Stable R1 envelope published as every tool's output schema."""

    ok: bool
    data: Any | None
    error: dict[str, str] | None


# Shared typed-input call-shape gate (one registration for stdio and remote).
# The SDK silently drops unknown top-level fields for scalar signatures, so
# typed tools get an explicit shape check here. The inner fields
# stay validated by the pydantic ``extra="forbid"`` input models.
_R5B_SHAPE_ERROR_ENVELOPE: dict[str, Any] = {
    "ok": False,
    "data": None,
    "error": {"code": "invalid_request", "message": "invalid tool arguments"},
}


def _r5b_shape_error_result() -> Any:
    from mcp.types import CallToolResult, TextContent

    envelope = dict(_R5B_SHAPE_ERROR_ENVELOPE)
    return CallToolResult(
        content=[
            TextContent(
                type="text",
                text=json.dumps(envelope, ensure_ascii=False),
            )
        ],
        structured_content=envelope,
        is_error=True,
    )


async def _typed_shape_middleware(ctx: Any, call_next: Callable[[Any], Any]) -> Any:
    """Shared typed-input call-shape gate for stdio and remote dispatch.

    ``arguments`` must be exactly ``{"input": <object>}`` for typed
    tools; any other shape is refused with a static ``invalid_request``
    result before the tool body can run. Tools outside the typed set and
    non-``tools/call`` methods pass through untouched (legacy five tools
    keep their exact wire behavior). On the remote transport this runs
    INSIDE the per-principal auth/scope middleware, so unauthorized callers
    cannot probe tool shapes.
    """
    if ctx.method != "tools/call":
        return await call_next(ctx)
    params = ctx.params if isinstance(ctx.params, dict) else {}
    name = params.get("name")
    if not isinstance(name, str) or name not in TYPED_INPUT_TOOLS:
        return await call_next(ctx)
    arguments = params.get("arguments")
    if not isinstance(arguments, dict) or set(arguments) != {"input"}:
        return _r5b_shape_error_result()
    if not isinstance(arguments.get("input"), dict):
        return _r5b_shape_error_result()
    return await call_next(ctx)


def _guarded_call(tool_name: str, fn) -> dict[str, Any]:
    """Execute a facade call with a last-resort boundary.

    The facade already maps every domain failure to an envelope; this guard
    exists so that a bug in the facade or adapter itself can never leak its
    ``str(e)`` or traceback onto the wire through the SDK's default rendering.
    The full diagnostic goes to stderr only.
    """
    try:
        envelope = fn()
    except Exception:
        logger.exception("unexpected error in MCP tool %s", tool_name)
        return dict(_INTERNAL_ENVELOPE)
    if envelope is None:  # pragma: no cover - defensive
        logger.exception("MCP tool %s returned no envelope", tool_name)
        return dict(_INTERNAL_ENVELOPE)
    return envelope


def build_mcp_server(
    interface: AgentInterface | None = None,
    *,
    interface_provider: Callable[[], AgentInterface] | None = None,
):
    """Build the shared R1/R3 MCP server tool surface.

    ``interface`` (stdio) or ``interface_provider`` (remote streamable HTTP)
    select the agent-facing facade. The provider is called per tool invocation
    so the request-scoped principal (set by the remote auth middleware) can
    supply the derived actor; the twelve tool registrations, schemas and
    bodies stay identical for both transports.
    """
    if interface is None and interface_provider is None:
        raise ValueError(
            "build_mcp_server requires interface or interface_provider"
        )
    if interface is not None and interface_provider is not None:
        raise ValueError(
            "interface and interface_provider are mutually exclusive"
        )

    def _current_interface() -> AgentInterface:
        if interface_provider is not None:
            return interface_provider()
        assert interface is not None
        return interface

    from mcp.server.mcpserver import MCPServer
    from mcp.types import CallToolResult, TextContent, ToolAnnotations

    server = MCPServer(
        "coordinate",
        version=__version__,
        description="Coordinate control-plane agent interface (stdio and streamable HTTP)",
    )

    # C2: one shared R5B call-shape gate for stdio and remote.  On the remote
    # transport the per-principal auth/scope middleware is inserted BEFORE
    # this gate by ``build_remote_mcp_app`` (outermost-first order), so
    # unauthorized callers cannot probe tool shapes.
    server.middleware.append(_typed_shape_middleware)

    read_only = ToolAnnotations(
        title="Read-only Coordinate query",
        read_only_hint=True,
        open_world_hint=False,
    )
    submit = ToolAnnotations(
        title="Idempotent Coordinate mutation",
        read_only_hint=False,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=False,
    )
    provision = ToolAnnotations(
        title="Idempotent external provisioning request",
        read_only_hint=False,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    )

    def _result(envelope: dict[str, Any]) -> Envelope:
        text = json.dumps(envelope, ensure_ascii=False)
        return CallToolResult(
            content=[TextContent(type="text", text=text)],
            structured_content=envelope,
            is_error=not envelope["ok"],
        )

    @server.tool(
        name="coordinate.operator_pending",
        title="Operator pending actions",
        description=(
            "List operator-pending actions and freshness-aware snapshot metadata for a "
            "workspace. Read-only; no harness refresh."
        ),
        annotations=read_only,
    )
    def operator_pending(workspace_id: str) -> Envelope:
        """Return pending actions and snapshot metadata for a workspace."""
        envelope = _guarded_call(
            "coordinate.operator_pending",
            lambda: _current_interface().operator_pending(workspace_id),
        )
        return _result(envelope)

    @server.tool(
        name="coordinate.workspace_audit",
        title="Workspace audit report",
        description=(
            "Produce a read-only drift/audit report for a workspace using the current "
            "harness files (refresh=False, same as the operator CLI path). Drift or a "
            "stale/unavailable harness snapshot is audit data, not a transport failure."
        ),
        annotations=read_only,
    )
    def workspace_audit(workspace_id: str) -> Envelope:
        """Return the workspace audit report (never refreshes harness state)."""
        envelope = _guarded_call(
            "coordinate.workspace_audit",
            lambda: _current_interface().workspace_audit(workspace_id),
        )
        return _result(envelope)

    @server.tool(
        name="coordinate.runtime_request_submit",
        title="Submit runtime request",
        description=(
            "Submit a bridge request, persisting a request.received event and a pending "
            "job with full idempotency semantics. Mutation tool: actor identity is fixed "
            "by the MCP server startup configuration and cannot be set by the caller. "
            "Requires a non-empty explicit idempotency_key; an exact replay returns the "
            "stored event/job without duplicating work, and a conflicting payload fails "
            "closed. Exact target_agent and typed routing_request are mutually exclusive; "
            "routing_request accepts only raw builder fields (required_capabilities, "
            "executor_definition_id, preferred_host_id, operator_override_agent_id, "
            "operator_override_reason)."
        ),
        annotations=submit,
    )
    def runtime_request_submit(
        workspace_id: str,
        prompt: str,
        origin: dict[str, Any],
        reply: dict[str, Any],
        idempotency_key: str,
        task_id: str | None = None,
        target_agent: str | None = None,
        routing_request: RoutingRequestInput | None = None,
        worktree_path: str | None = None,
    ) -> Envelope:
        """Submit a runtime request with exact or routed targeting."""
        envelope = _guarded_call(
            "coordinate.runtime_request_submit",
            lambda: _current_interface().runtime_request_submit(
                workspace_id=workspace_id,
                prompt=prompt,
                origin=origin,
                reply=reply,
                task_id=task_id,
                target_agent=target_agent,
                routing_request=(
                    routing_request.model_dump()
                    if routing_request is not None
                    else None
                ),
                worktree_path=worktree_path,
                idempotency_key=idempotency_key,
            ),
        )
        return _result(envelope)

    @server.tool(
        name="coordinate.runtime_job_get",
        title="Get runtime job",
        description=(
            "Return the full JSON-compatible projection of one runtime job by id. "
            "Read-only; never claims the job."
        ),
        annotations=read_only,
    )
    def runtime_job_get(job_id: str) -> Envelope:
        """Return one job projection; not_found when the job does not exist."""
        envelope = _guarded_call(
            "coordinate.runtime_job_get",
            lambda: _current_interface().runtime_job_get(job_id),
        )
        return _result(envelope)

    @server.tool(
        name="coordinate.runtime_agent_list",
        title="List runtime agents",
        description=(
            "List all registered runtime clients (agents table) with their current "
            "online state, host, capabilities and last-seen time. Read-only; no filters "
            "in R1."
        ),
        annotations=read_only,
    )
    def runtime_agent_list() -> Envelope:
        """Return the structured list of registered runtime clients."""
        envelope = _guarded_call(
            "coordinate.runtime_agent_list",
            lambda: _current_interface().runtime_agent_list(),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_CHANNEL_CREATE,
        title="Create and bind Discord workspace channel",
        description=(
            "Record or replay one durable Discord channel provisioning request. "
            "The Coordinator daemon is the only Discord mutation executor; this "
            "tool returns pending, provisioned, or failed state."
        ),
        annotations=provision,
    )
    def channel_create(input: ChannelCreateInput) -> Envelope:
        envelope = _guarded_call(
            TOOL_CHANNEL_CREATE,
            lambda: _current_interface().channel_create(
                workspace_id=input.workspace_id,
                channel_name=input.channel_name,
                idempotency_key=input.idempotency_key,
            ),
        )
        return _result(envelope)

    # -- R5B: task create record half + completion receipt lifecycle ---------
    # Six typed scalar tools shared by stdio and remote HTTP. Each takes a
    # single flat pydantic input model with extra="forbid": forged fields
    # (payload, requester, authorized_actor, actor, unknown keys) are
    # rejected by the SDK argument validation before the tool body runs, and
    # the remote middleware re-checks the exact input shape plus the
    # workspace scope before dispatch.

    @server.tool(
        name=TOOL_TASK_CREATE_RECORD,
        title="Task create record half",
        description=(
            "Server half of host-aware task create: re-derive the deployed "
            "checklist envelope and fingerprints from the registered "
            "workspace, then write the DB task mirror and plan.ready event. "
            "Scalar-only contract — no payload dict, no arbitrary path, no "
            "actor (fixed to the request principal). Requires the deployed "
            "file half; any drift fails closed with zero DB mutation."
        ),
        annotations=submit,
    )
    def task_create_record(input: TaskCreateRecordInput) -> Envelope:
        """Apply the task.create record half from the deployed file half."""
        envelope = _guarded_call(
            "coordinate.task_create_record",
            lambda: _current_interface().task_create_record(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_COMPLETION_PREPARE,
        title="Prepare completion receipt",
        description=(
            "Validate the closeout/review/forge gate on the control plane "
            "and issue a one-time completion.authorized receipt binding the "
            "host-aware mark-done lifecycle. requester and authorized_actor "
            "are fixed to the request-scoped principal actor and cannot be "
            "set by the caller."
        ),
        annotations=submit,
    )
    def completion_prepare(input: CompletionPrepareInput) -> Envelope:
        """Issue a one-time completion receipt for the principal actor."""
        envelope = _guarded_call(
            "coordinate.completion_prepare",
            lambda: _current_interface().completion_prepare(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_COMPLETION_PREFLIGHT,
        title="Preflight completion receipt",
        description=(
            "Read-only: re-derive the authoritative receipt binding "
            "(workspace/task/status/expiry) from the control-plane ledger. "
            "The coding host calls this before mutating its canonical "
            "checklist so it never trusts its own claims."
        ),
        annotations=read_only,
    )
    def completion_preflight(input: CompletionPreflightInput) -> Envelope:
        """Return the authoritative receipt binding for the host."""
        envelope = _guarded_call(
            "coordinate.completion_preflight",
            lambda: _current_interface().completion_preflight(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_COMPLETION_CLAIM,
        title="Claim completion receipt",
        description=(
            "Atomically reserve a receipt authorized -> claimed on the "
            "control plane, recording before/expected-after fingerprints. "
            "Called BEFORE the canonical checklist write; actor is fixed to "
            "the request principal."
        ),
        annotations=submit,
    )
    def completion_claim(input: CompletionClaimInput) -> Envelope:
        """Reserve the receipt before the local canonical write."""
        envelope = _guarded_call(
            "coordinate.completion_claim",
            lambda: _current_interface().completion_claim(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_COMPLETION_APPLY,
        title="Apply completion receipt",
        description=(
            "Acknowledge a claimed receipt -> applied on the control plane, "
            "recording the actual after-fingerprint. Called AFTER the "
            "canonical checklist write lands; actor is fixed to the request "
            "principal."
        ),
        annotations=submit,
    )
    def completion_apply(input: CompletionApplyInput) -> Envelope:
        """Acknowledge the receipt after the local canonical write."""
        envelope = _guarded_call(
            "coordinate.completion_apply",
            lambda: _current_interface().completion_apply(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    @server.tool(
        name=TOOL_COMPLETION_CONSUME,
        title="Consume completion receipt",
        description=(
            "Re-verify the deployed harness (done/closed with a matching "
            "fingerprint) and atomically write task.done + completion.consumed. "
            "workspace_id is scoped by the middleware first and bound against "
            "the receipt by the domain; actor is fixed to the request "
            "principal."
        ),
        annotations=submit,
    )
    def completion_consume(input: CompletionConsumeInput) -> Envelope:
        """Consume the receipt against the deployed harness."""
        envelope = _guarded_call(
            "coordinate.completion_consume",
            lambda: _current_interface().completion_consume(
                **input.model_dump()
            ),
        )
        return _result(envelope)

    return server
